modLoader="javafml"
loaderVersion="[31,]"
logoFile="logo.png"
authors="bageldotjpg & Pugz"
credits="*Endergized*, Josh, Bratistolf, Rohan, Arobazz, jöllipölli, qsefthuopq, and Dolores_McDoodle"

[[mods]]
modId="bloomful"
version="${file.jarVersion}"
displayName="Bloomful"
description='''
See Flower Forests in full bloom!
'''

[[dependencies.bloomful]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"