modLoader="javafml"
loaderVersion="[28,]"
logoFile="logo.png"
authors="Pugz"
credits="Endergized, Josh, Bratiswolf, Rohan, Arobazz, and jöllipölli"

[[mods]]
    modId="bloomful"
    version="1.0.0"
    displayName="Bloomful"
    description='''
    See Flower Forests in full bloom!
    '''