modLoader="javafml"
loaderVersion="[28,]"
logoFile="logo.png"
authors="Pugz"
credits="*Endergized*, Josh, Bratiswolf, Rohan, Arobazz, jöllipölli, and qsefthuopq"

[[mods]]
modId="bloomful"
version="1.2.0"
displayName="Bloomful"
description='''
See Flower Forests in full bloom!
'''

[[dependencies.bloomful]]
    modId="forge"
    mandatory=true
    versionRange="[24,)"
    ordering="NONE"
    side="BOTH"